name: GitHub Action Ubuntu
run-name: ${{ github.event_name }} GitHub Action triggered by ${{ github.actor }}
on: [pull_request]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      - name: Build the stuff
        run: |
          cd ${{ github.workspace }}
          make
      - name: Run tests
        run: |
          make check
