name: GitHub Action Windows
run-name: ${{ github.event_name }} GitHub Action triggered by ${{ github.actor }}
on: [pull_request]
jobs:
  Run-Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
        os: [windows-2022]
        carch: [x86_64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Disable git autocrlf
        run: git config --global core.autocrlf false
        shell: cmd
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install tools
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-toolchain
      - name: Build the stuff
        run: |
          # need to run shell explicitly to set up path, running make directly fails
          .github/msys.sh
      - name: Run tests
        run: |
          make check
